version: "3.7"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - eventdriven

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami
    networks:
      - eventdriven

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - eventdriven

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - eventdriven

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elasticsearch-data:


networks:
  eventdriven:
    external: true
